include $(PWD)/config.mk
FOLDER_NAME = examples

all:
	@make -s -C AccelGyroMag
	@make -s -C ADC
	@make -s -C AHRS
	@make -s -C Barometer
	@make -s -C GPS
	@make -s -C LED2
	@make -s -C Servo
	@make -s -C RCInput
